In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('Train.csv')

In [3]:
df_target = pd.read_csv('TrainTargets.csv')

In [4]:
td = pd.read_csv('Test.csv')

In [5]:
sub = pd.read_csv('SampleSubmission.csv')

In [6]:
df.head()

Unnamed: 0    AP1    AP2    AP3    AP4    AP5    AP6    AP7    AP8    AP9  \
0       STA1 -64.87 -75.67 -85.98 -68.34 -77.09 -86.38 -83.07 -85.13 -89.73   
1       STA2 -79.89 -67.19 -75.01 -79.89 -67.19 -75.01 -85.82 -82.19 -83.96   
2       STA3 -87.19 -77.41 -55.58 -88.46 -81.24 -74.39 -91.72 -87.85 -85.67   
3       STA4 -81.35 -82.71 -87.90 -66.55 -72.62 -84.37 -69.83 -74.66 -84.86   
4       STA5 -85.33 -82.09 -84.40 -78.77 -66.72 -76.34 -78.77 -66.72 -76.34   

   TP1  TP2  TP3  TP4  TP5  TP6  TP7  TP8  TP9  Deployment  
0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN        9391  
1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN        9391  
2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN        9391  
3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN        9391  
4  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN        9391

In [7]:
df_target.head()

ID  Target
0   Deployment10000_TXOP100_AP3_STA9   108.0
1  Deployment10000_TXOP100_AP4_STA13   348.0
2  Deployment10000_TXOP100_AP9_STA36   210.0
3   Deployment10000_TXOP10_AP3_STA11   156.0
4   Deployment10000_TXOP10_AP7_STA25     0.0

In [8]:
sub.head()

ID  Target
0  Deployment1000_TXOP100_AP6_STA17       0
1   Deployment1000_TXOP10_AP6_STA17       0
2   Deployment1000_TXOP10_AP8_STA23       0
3    Deployment1000_TXOP11_AP1_STA3       0
4    Deployment1000_TXOP12_AP2_STA5       0

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 888397 entries, 0 to 888396
Data columns (total 20 columns):
 #   Column      Non-Null Count   Dtype  
---  ------      --------------   -----  
 0   Unnamed: 0  888397 non-null  object 
 1   AP1         888397 non-null  float64
 2   AP2         888397 non-null  float64
 3   AP3         888397 non-null  float64
 4   AP4         888397 non-null  float64
 5   AP5         888397 non-null  float64
 6   AP6         888397 non-null  float64
 7   AP7         888397 non-null  float64
 8   AP8         888397 non-null  float64
 9   AP9         888397 non-null  float64
 10  TP1         700000 non-null  float64
 11  TP2         700000 non-null  float64
 12  TP3         700000 non-null  float64
 13  TP4         700000 non-null  float64
 14  TP5         700000 non-null  float64
 15  TP6         700000 non-null  float64
 16  TP7         700000 non-null  float64
 17  TP8         700000 non-null  float64
 18  TP9         700000 non-null  float64
 19  De

In [10]:
df_target.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1749596 entries, 0 to 1749595
Data columns (total 2 columns):
 #   Column  Dtype  
---  ------  -----  
 0   ID      object 
 1   Target  float64
dtypes: float64(1), object(1)
memory usage: 26.7+ MB


In [11]:
td.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 382008 entries, 0 to 382007
Data columns (total 11 columns):
 #   Column      Non-Null Count   Dtype  
---  ------      --------------   -----  
 0   Unnamed: 0  382008 non-null  object 
 1   AP1         382008 non-null  float64
 2   AP2         382008 non-null  float64
 3   AP3         382008 non-null  float64
 4   AP4         382008 non-null  float64
 5   AP5         382008 non-null  float64
 6   AP6         382008 non-null  float64
 7   AP7         382008 non-null  float64
 8   AP8         382008 non-null  float64
 9   AP9         382008 non-null  float64
 10  Deployment  382008 non-null  int64  
dtypes: float64(9), int64(1), object(1)
memory usage: 32.1+ MB


In [12]:
sub.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 749924 entries, 0 to 749923
Data columns (total 2 columns):
 #   Column  Non-Null Count   Dtype 
---  ------  --------------   ----- 
 0   ID      749924 non-null  object
 1   Target  749924 non-null  int64 
dtypes: int64(1), object(1)
memory usage: 11.4+ MB


# First most Prepare the Data

the first thing i most made a Data frame from\
`Deployment Txop Ap STA RSSI`

 **lets do the following**
* make a data frame from deployment toxp ap sta rssi
* make sample data from big data set

In [13]:
dftest = df[:18]

In [14]:
dftest.head()

Unnamed: 0    AP1    AP2    AP3    AP4    AP5    AP6    AP7    AP8    AP9  \
0       STA1 -64.87 -75.67 -85.98 -68.34 -77.09 -86.38 -83.07 -85.13 -89.73   
1       STA2 -79.89 -67.19 -75.01 -79.89 -67.19 -75.01 -85.82 -82.19 -83.96   
2       STA3 -87.19 -77.41 -55.58 -88.46 -81.24 -74.39 -91.72 -87.85 -85.67   
3       STA4 -81.35 -82.71 -87.90 -66.55 -72.62 -84.37 -69.83 -74.66 -84.86   
4       STA5 -85.33 -82.09 -84.40 -78.77 -66.72 -76.34 -78.77 -66.72 -76.34   

   TP1  TP2  TP3  TP4  TP5  TP6  TP7  TP8  TP9  Deployment  
0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN        9391  
1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN        9391  
2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN        9391  
3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN        9391  
4  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN        9391

In [15]:
df_ali = pd.DataFrame(dftest['Deployment'][:9])

In [16]:
df_ali['STA'] = np.arange(1,10)

In [17]:
df_ali['Ap'] = np.arange(1,10)

**Creating** `RSSI` 

In [18]:
df_ali['RSSI'] = np.random.randint(0,64,9)

In [19]:
df_ali['TPXO'] = np.arange(9)

In [20]:
df_ali['Target'] = np.random.randint(1,255,9)

In [21]:
df_ali['Number of STA'] = len(df_ali['STA'])

In [22]:
df_ali

Deployment  STA  Ap  RSSI  TPXO  Target  Number of STA
0        9391    1   1     7     0      44              9
1        9391    2   2    55     1     222              9
2        9391    3   3    39     2     166              9
3        9391    4   4    27     3     107              9
4        9391    5   5    57     4      11              9
5        9391    6   6    47     5     212              9
6        9391    7   7    15     6      75              9
7        9391    8   8     9     7     201              9
8        9391    9   9    16     8      57              9

yes Now lets Creatting ali data set from small data apove\
step by step

In [23]:
dftest.head(20)

Unnamed: 0    AP1    AP2    AP3    AP4    AP5    AP6    AP7    AP8    AP9  \
0        STA1 -64.87 -75.67 -85.98 -68.34 -77.09 -86.38 -83.07 -85.13 -89.73   
1        STA2 -79.89 -67.19 -75.01 -79.89 -67.19 -75.01 -85.82 -82.19 -83.96   
2        STA3 -87.19 -77.41 -55.58 -88.46 -81.24 -74.39 -91.72 -87.85 -85.67   
3        STA4 -81.35 -82.71 -87.90 -66.55 -72.62 -84.37 -69.83 -74.66 -84.86   
4        STA5 -85.33 -82.09 -84.40 -78.77 -66.72 -76.34 -78.77 -66.72 -76.34   
5        STA6 -90.66 -85.15 -80.28 -88.69 -80.28 -65.12 -89.23 -81.82 -71.76   
6        STA7 -85.04 -88.02 -92.19 -73.51 -82.33 -89.43 -63.71 -80.06 -88.61   
7        STA8 -87.85 -85.67 -87.19 -81.24 -74.39 -79.56 -77.41 -55.58 -74.39   
8        STA9 -94.79 -91.90 -90.02 -91.71 -86.82 -82.58 -89.53 -81.92 -69.12   
9       TXOP1   1.00   2.00   0.00   0.00   5.00   0.00   7.00   0.00   0.00   
10      TXOP2   1.00   2.00   0.00   0.00   0.00   6.00   0.00   0.00   0.00   
11      TXOP3   0.00   2.00   0.00   0.00   0.00   6.00   0.00   0.00   0.00   
12      TXOP4   0.00   0.00   3.00   0.00   0.00   6.00   0.00   0.00   0.00   
13      TXOP5   0.00   0.00   0.00   0.00   5.00   0.00   0.00   0.00   0.00   
14      TXOP6   0.00   0.00   0.00   0.00   0.00   6.00   7.00   0.00   0.00   
15      TXOP7   0.00   0.00   0.00   0.00   5.00   0.00   7.00   8.00   9.00   
16      TXOP8   1.00   2.00   0.00   0.00   0.00   0.00   7.00   0.00   0.00   
17      TXOP9   0.00   0.00   3.00   4.00   5.00   6.00   0.00   0.00   0.00   

     TP1   TP2    TP3  TP4    TP5    TP6    TP7   TP8   TP9  Deployment  
0    NaN   NaN    NaN  NaN    NaN    NaN    NaN   NaN   NaN        9391  
1    NaN   NaN    NaN  NaN    NaN    NaN    NaN   NaN   NaN        9391  
2    NaN   NaN    NaN  NaN    NaN    NaN    NaN   NaN   NaN        9391  
3    NaN   NaN    NaN  NaN    NaN    NaN    NaN   NaN   NaN        9391  
4    NaN   NaN    NaN  NaN    NaN    NaN    NaN   NaN   NaN        9391  
5    NaN   NaN    NaN  NaN    NaN    NaN    NaN   NaN   NaN        9391  
6    NaN   NaN    NaN  NaN    NaN    NaN    NaN   NaN   NaN        9391  
7    NaN   NaN    NaN  NaN    NaN    NaN    NaN   NaN   NaN        9391  
8    NaN   NaN    NaN  NaN    NaN    NaN    NaN   NaN   NaN        9391  
9   30.0   0.0    0.0  0.0   54.0    0.0  108.0   0.0   0.0        9391  
10  54.0  30.0    0.0  0.0    0.0  156.0    0.0   0.0   0.0        9391  
11   0.0  30.0    0.0  0.0    0.0  156.0    0.0   0.0   0.0        9391  
12   0.0   0.0  156.0  0.0    0.0   78.0    0.0   0.0   0.0        9391  
13   0.0   0.0    0.0  0.0  258.0    0.0    0.0   0.0   0.0        9391  
14   0.0   0.0    0.0  0.0    0.0  156.0  234.0   0.0   0.0        9391  
15   0.0   0.0    0.0  0.0    0.0    0.0   78.0  78.0  54.0        9391  
16  54.0  54.0    0.0  0.0    0.0    0.0  156.0   0.0   0.0        9391  
17   0.0   0.0  108.0  0.0   30.0   78.0    0.0   0.0   0.0        9391

In [24]:
# dftest[dftest['Unnamed: 0'].str.contains("TXO")]

## 2- Creating `Station` Columns (STA)

In [25]:
mk = dftest[dftest['Unnamed: 0'].str.contains("TXOP")][['AP1' ,'AP2','AP3','AP4','AP5','AP6','AP7','AP8','AP9']]

In [26]:
io = np.array(mk,dtype=int)
io

array([[1, 2, 0, 0, 5, 0, 7, 0, 0],
       [1, 2, 0, 0, 0, 6, 0, 0, 0],
       [0, 2, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 3, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 6, 7, 0, 0],
       [0, 0, 0, 0, 5, 0, 7, 8, 9],
       [1, 2, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 3, 4, 5, 6, 0, 0, 0]])

In [27]:
oi = io[np.where(io!=0)]

oi

array([1, 2, 5, 7, 1, 2, 6, 2, 6, 3, 6, 5, 6, 7, 5, 7, 8, 9, 1, 2, 7, 3,
       4, 5, 6])

In [28]:
len(io[np.where(io!=0)])

25

In [29]:
len(oi)

25

In [30]:
df_ali = pd.DataFrame(oi,columns=['SAT'])

In [31]:
df_ali.head()

SAT
0    1
1    2
2    5
3    7
4    1

## 3- Creating `Access Point` Columns (AP)

In [32]:
num = np.arange(1,10)
num

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
ap = np.array([num for n in range(len(mk))])

In [34]:
ap

array([[1, 2, 3, 4, 5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [35]:
pa = ap[np.where(io!=0)]
pa

array([1, 2, 5, 7, 1, 2, 6, 2, 6, 3, 6, 5, 6, 7, 5, 7, 8, 9, 1, 2, 7, 3,
       4, 5, 6])

In [36]:
df_ali['AP'] = pa

## 4- Creating `Received Signal Strength Indicator` Columns (RSSI)

In [37]:
dftest[dftest['Unnamed: 0'].str.contains("STA")][['Unnamed: 0','AP1' ,'AP2','AP3','AP4','AP5','AP6','AP7','AP8','AP9']]

Unnamed: 0    AP1    AP2    AP3    AP4    AP5    AP6    AP7    AP8    AP9
0       STA1 -64.87 -75.67 -85.98 -68.34 -77.09 -86.38 -83.07 -85.13 -89.73
1       STA2 -79.89 -67.19 -75.01 -79.89 -67.19 -75.01 -85.82 -82.19 -83.96
2       STA3 -87.19 -77.41 -55.58 -88.46 -81.24 -74.39 -91.72 -87.85 -85.67
3       STA4 -81.35 -82.71 -87.90 -66.55 -72.62 -84.37 -69.83 -74.66 -84.86
4       STA5 -85.33 -82.09 -84.40 -78.77 -66.72 -76.34 -78.77 -66.72 -76.34
5       STA6 -90.66 -85.15 -80.28 -88.69 -80.28 -65.12 -89.23 -81.82 -71.76
6       STA7 -85.04 -88.02 -92.19 -73.51 -82.33 -89.43 -63.71 -80.06 -88.61
7       STA8 -87.85 -85.67 -87.19 -81.24 -74.39 -79.56 -77.41 -55.58 -74.39
8       STA9 -94.79 -91.90 -90.02 -91.71 -86.82 -82.58 -89.53 -81.92 -69.12

In [38]:
# int(dftest['AP4'].loc[((dftest['Unnamed: 0'] == 'STA2'))][1])

In [39]:
df_ali['RSSI'] = df_ali.apply(lambda row: float(dftest[f'AP{int(row.AP)}'].loc[((dftest['Unnamed: 0'] == f'STA{int(row.SAT)}'))]) ,axis=1)

In [40]:
df_ali.AP = df_ali.AP.apply(np.int64)
df_ali.SAT = df_ali.SAT.apply(np.int64)

In [41]:
df_ali.head()

SAT  AP   RSSI
0    1   1 -64.87
1    2   2 -67.19
2    5   5 -66.72
3    7   7 -63.71
4    1   1 -64.87

# with numpy

In [42]:
dfrrsi = dftest[dftest['Unnamed: 0'].str.contains("STA")][['AP1' ,'AP2','AP3','AP4','AP5','AP6','AP7','AP8','AP9','Deployment']]


In [43]:
# df_ali = df_ali.drop('RSSI',axis=1)

In [44]:
df_alinp = np.array(df_ali)
dftestnp = np.array(dftest)
dfrrsinp = np.array(dfrrsi)

In [45]:
dfrrsinp

array([[ -64.87,  -75.67,  -85.98,  -68.34,  -77.09,  -86.38,  -83.07,
         -85.13,  -89.73, 9391.  ],
       [ -79.89,  -67.19,  -75.01,  -79.89,  -67.19,  -75.01,  -85.82,
         -82.19,  -83.96, 9391.  ],
       [ -87.19,  -77.41,  -55.58,  -88.46,  -81.24,  -74.39,  -91.72,
         -87.85,  -85.67, 9391.  ],
       [ -81.35,  -82.71,  -87.9 ,  -66.55,  -72.62,  -84.37,  -69.83,
         -74.66,  -84.86, 9391.  ],
       [ -85.33,  -82.09,  -84.4 ,  -78.77,  -66.72,  -76.34,  -78.77,
         -66.72,  -76.34, 9391.  ],
       [ -90.66,  -85.15,  -80.28,  -88.69,  -80.28,  -65.12,  -89.23,
         -81.82,  -71.76, 9391.  ],
       [ -85.04,  -88.02,  -92.19,  -73.51,  -82.33,  -89.43,  -63.71,
         -80.06,  -88.61, 9391.  ],
       [ -87.85,  -85.67,  -87.19,  -81.24,  -74.39,  -79.56,  -77.41,
         -55.58,  -74.39, 9391.  ],
       [ -94.79,  -91.9 ,  -90.02,  -91.71,  -86.82,  -82.58,  -89.53,
         -81.92,  -69.12, 9391.  ]])

In [46]:
dfrrsinp[1][1]
# np.isin()

df_alinp
df_alinp[:, : 2]

array([[1., 1.],
       [2., 2.],
       [5., 5.],
       [7., 7.],
       [1., 1.],
       [2., 2.],
       [6., 6.],
       [2., 2.],
       [6., 6.],
       [3., 3.],
       [6., 6.],
       [5., 5.],
       [6., 6.],
       [7., 7.],
       [5., 5.],
       [7., 7.],
       [8., 8.],
       [9., 9.],
       [1., 1.],
       [2., 2.],
       [7., 7.],
       [3., 3.],
       [4., 4.],
       [5., 5.],
       [6., 6.]])

In [47]:
a = dfrrsinp

In [48]:
dfrrsinp[:, :][0][1]
np.where(a,)

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4,
        4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6,
        6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8,
        8, 8], dtype=int64),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1,
        2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3,
        4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5,
        6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7,
        8, 9], dtype=int64))

## 5- Creating `Transmit Opportunity ` Columns (TPOX)

In [49]:
io.shape, io.shape[1] 

((9, 9), 9)

In [50]:
io

array([[1, 2, 0, 0, 5, 0, 7, 0, 0],
       [1, 2, 0, 0, 0, 6, 0, 0, 0],
       [0, 2, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 3, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 6, 7, 0, 0],
       [0, 0, 0, 0, 5, 0, 7, 8, 9],
       [1, 2, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 3, 4, 5, 6, 0, 0, 0]])

In [51]:
we = np.array([np.full(9,n) for n in range(1,io.shape[1]+1)])

In [52]:
Txo = we[np.where(io!=0)]

In [53]:
df_ali['TXOP'] = Txo

In [54]:
df_ali.head()

SAT  AP   RSSI  TXOP
0    1   1 -64.87     1
1    2   2 -67.19     1
2    5   5 -66.72     1
3    7   7 -63.71     1
4    1   1 -64.87     2

## Creat a Target TP

In [55]:
cx = np.array(dftest[dftest['Unnamed: 0'].str.contains("TXOP")][['TP1' ,'TP2','TP3','TP4','TP5','TP6','TP7','TP8','TP9']],dtype =int)

In [56]:
ps = cx[np.where(io!=0)]

In [57]:
len(ps)

25

In [58]:
df_ali['Target'] = ps

In [59]:
df_ali.head()

SAT  AP   RSSI  TXOP  Target
0    1   1 -64.87     1      30
1    2   2 -67.19     1       0
2    5   5 -66.72     1      54
3    7   7 -63.71     1     108
4    1   1 -64.87     2      54

# WondorFull

In [60]:
df_ali.to_csv('fdafsda.csv',index=False)

# Huge DATA SET

# `STA`

In [61]:
km = df[df['Unnamed: 0'].str.contains("TXOP")][['AP1' ,'AP2','AP3','AP4','AP5','AP6','AP7','AP8','AP9']]
km.head()

AP1  AP2  AP3  AP4  AP5  AP6  AP7  AP8  AP9
9   1.0  2.0  0.0  0.0  5.0  0.0  7.0  0.0  0.0
10  1.0  2.0  0.0  0.0  0.0  6.0  0.0  0.0  0.0
11  0.0  2.0  0.0  0.0  0.0  6.0  0.0  0.0  0.0
12  0.0  0.0  3.0  0.0  0.0  6.0  0.0  0.0  0.0
13  0.0  0.0  0.0  0.0  5.0  0.0  0.0  0.0  0.0

In [62]:
hf = np.array(km,dtype=int)
hf

array([[ 1,  2,  0, ...,  7,  0,  0],
       [ 1,  2,  0, ...,  0,  0,  0],
       [ 0,  2,  0, ...,  0,  0,  0],
       ...,
       [ 2,  0,  6, ...,  0,  0,  0],
       [ 2,  0,  0, ...,  0,  0,  0],
       [ 0,  3,  0, ...,  0, 15,  0]])

In [63]:
fh = hf[np.where(hf!=0)]

In [64]:
len(hf)

700000

In [65]:
len(fh)

1749596

# `AP`

In [66]:
fap= np.array([num for n in range(len(km))])

In [67]:
paf = fap[np.where(hf!=0)]

In [68]:
len(paf)

1749596

In [69]:
dffull = pd.DataFrame({"STA":fh,"AP":paf})

In [70]:
dffull.STA = dffull.STA.apply(np.int64)
dffull.AP = dffull.AP.apply(np.int64)

In [71]:
dffull['Deployment'] = 9391

# `RSSI`

In [72]:
dffull.head()

STA  AP  Deployment
0    1   1        9391
1    2   2        9391
2    5   5        9391
3    7   7        9391
4    1   1        9391

In [73]:
a = (np.array(dffull['AP']))-1
b = (np.array(dffull['STA']))-1

In [74]:
uj = np.array(dftest[dftest['Unnamed: 0'].str.contains("STA")][['AP1' ,'AP2','AP3','AP4','AP5','AP6','AP7','AP8','AP9']])

In [75]:
uj

array([[-64.87, -75.67, -85.98, -68.34, -77.09, -86.38, -83.07, -85.13,
        -89.73],
       [-79.89, -67.19, -75.01, -79.89, -67.19, -75.01, -85.82, -82.19,
        -83.96],
       [-87.19, -77.41, -55.58, -88.46, -81.24, -74.39, -91.72, -87.85,
        -85.67],
       [-81.35, -82.71, -87.9 , -66.55, -72.62, -84.37, -69.83, -74.66,
        -84.86],
       [-85.33, -82.09, -84.4 , -78.77, -66.72, -76.34, -78.77, -66.72,
        -76.34],
       [-90.66, -85.15, -80.28, -88.69, -80.28, -65.12, -89.23, -81.82,
        -71.76],
       [-85.04, -88.02, -92.19, -73.51, -82.33, -89.43, -63.71, -80.06,
        -88.61],
       [-87.85, -85.67, -87.19, -81.24, -74.39, -79.56, -77.41, -55.58,
        -74.39],
       [-94.79, -91.9 , -90.02, -91.71, -86.82, -82.58, -89.53, -81.92,
        -69.12]])

In [76]:
uj[3][3]

-66.55

In [77]:
def preprocess(data,is_train=True):

  dep=data['Deployment'].unique()
  rows=[]
  for dd in dep:
    df=data[data.Deployment==dd]
    
    toxp_map=dict()
    rssi_map=dict()
    flag=0
    for i, j in df.iterrows():
        if('STA' in j[0]):
          rssi_map[j[0]]={f'AP{i}':j[i] for i in range(1,10)}
        else:
          toxp_map[j[0]]={(j.index[i],'STA'+str(int(j[i]))) for i in range(1,10)}

    
    for exp,elems in toxp_map.items():
      rows1=[]
      for e in elems:
        row=[dd,exp]
        if(e[-1]!='STA0'):
          row.extend([e[0],e[1],rssi_map[e[-1]][e[0]]])
          rows.append(row)
  

      #rows.extend(rows1)
    
  data=pd.DataFrame(rows)
  data.columns = ['Deployment','TXOP','mainAP','mainSTA','mainRSSI']
  data['ID']='Deployment'+data['Deployment'].astype(str)+'_'+data['TXOP']+'_'+data['mainAP']+'_'+data['mainSTA']
  if(is_train):
    tt=pd.read_csv('TrainTargets.csv')
    data=pd.merge(data,tt,on='ID')
  
  
  return data
  





     


In [78]:
train = pd.read_csv('Train.csv')

In [79]:
train_df = preprocess(train)

In [80]:
train_df.head()

Deployment   TXOP mainAP mainSTA  mainRSSI                             ID  \
0        9391  TXOP1    AP1    STA1    -64.87  Deployment9391_TXOP1_AP1_STA1   
1        9391  TXOP1    AP7    STA7    -63.71  Deployment9391_TXOP1_AP7_STA7   
2        9391  TXOP1    AP2    STA2    -67.19  Deployment9391_TXOP1_AP2_STA2   
3        9391  TXOP1    AP5    STA5    -66.72  Deployment9391_TXOP1_AP5_STA5   
4        9391  TXOP2    AP6    STA6    -65.12  Deployment9391_TXOP2_AP6_STA6   

   Target  
0    30.0  
1   108.0  
2     0.0  
3    54.0  
4   156.0

In [81]:
AP = np.char.lstrip(np.array(train_df['mainAP']).astype(str),'AP')
STA = np.char.lstrip(np.array(train_df['mainSTA']).astype(str),'STA')
TXOP = np.char.lstrip(np.array(train_df['TXOP']).astype(str),'TXOP')
Target = np.array(train_df['Target']).astype(int)
Deployment = np.array(train_df['Deployment'])
RSSI = np.array(train_df['mainRSSI'])

In [82]:
np.array(train_df['Deployment'])

array([9391, 9391, 9391, ..., 3934, 3934, 3934], dtype=int64)

In [83]:
frame = {'Deployment':Deployment
        ,'STA':STA
        ,'Ap':AP
        ,'RSSI':RSSI
        ,'TXOP':TXOP
        ,'Target':Target}

In [84]:
nice = pd.DataFrame(frame)

In [85]:
# nice.to_csv('nice.csv',index=False)

In [86]:
td = pd.read_csv('Test.csv')

In [87]:
test = preprocess(td,False)

In [88]:
test.head()

Deployment   TXOP mainAP mainSTA  mainRSSI                              ID
0        9373  TXOP1    AP9   STA35    -69.12  Deployment9373_TXOP1_AP9_STA35
1        9373  TXOP2    AP4   STA13    -64.87  Deployment9373_TXOP2_AP4_STA13
2        9373  TXOP2    AP3    STA9    -63.71   Deployment9373_TXOP2_AP3_STA9
3        9373  TXOP2    AP1    STA3    -67.19   Deployment9373_TXOP2_AP1_STA3
4        9373  TXOP3    AP4   STA14    -65.58  Deployment9373_TXOP3_AP4_STA14

In [89]:
AP = np.char.lstrip(np.array(test['mainAP']).astype(str),'AP')
STA = np.char.lstrip(np.array(test['mainSTA']).astype(str),'STA')
TXOP = np.char.lstrip(np.array(test['TXOP']).astype(str),'TXOP')
# Target = np.array(train_df['Target']).astype(int)
Deployment = np.array(test['Deployment'])
RSSI = np.array(test['mainRSSI'])

In [90]:
frame = {'Deployment':Deployment
        ,'STA':STA
        ,'Ap':AP
        ,'RSSI':RSSI
        ,'TXOP':TXOP}

In [91]:
nicetest = pd.DataFrame(frame)

In [92]:
# nicetest.to_csv('nicetest.csv',index=False)

In [93]:
nicetest

Deployment STA Ap   RSSI TXOP
0             9373  35  9 -69.12    1
1             9373  13  4 -64.87    2
2             9373   9  3 -63.71    2
3             9373   3  1 -67.19    2
4             9373  14  4 -65.58    3
...            ...  .. ..    ...  ...
749919        5144   5  3 -63.71   98
749920        5144   5  3 -63.71   99
749921        5144  17  9 -65.58   99
749922        5144  16  8 -64.61  100
749923        5144   7  4 -69.12  100

[749924 rows x 5 columns]

In [94]:
df.head()

Unnamed: 0    AP1    AP2    AP3    AP4    AP5    AP6    AP7    AP8    AP9  \
0       STA1 -64.87 -75.67 -85.98 -68.34 -77.09 -86.38 -83.07 -85.13 -89.73   
1       STA2 -79.89 -67.19 -75.01 -79.89 -67.19 -75.01 -85.82 -82.19 -83.96   
2       STA3 -87.19 -77.41 -55.58 -88.46 -81.24 -74.39 -91.72 -87.85 -85.67   
3       STA4 -81.35 -82.71 -87.90 -66.55 -72.62 -84.37 -69.83 -74.66 -84.86   
4       STA5 -85.33 -82.09 -84.40 -78.77 -66.72 -76.34 -78.77 -66.72 -76.34   

   TP1  TP2  TP3  TP4  TP5  TP6  TP7  TP8  TP9  Deployment  
0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN        9391  
1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN        9391  
2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN        9391  
3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN        9391  
4  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN        9391